AWSTemplateFormatVersion: '2010-09-09'
Description: Create CloudFront.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - EnvType
          - ProjectId
      - Label:
          default: CloudFront Configuration
        Parameters:
          - CertificateName
          - CertificateARN
          - OriginCertificateName
    ParameterLabels:
      EnvType:
        default: Environment type.
      ProjectId:
        default: Project name id.
      CertificateName:
        default: CertificateName
      CertificateARN:
        default: CertificateARN
      OriginCertificateName:
        default: OriginCertificateName

Parameters:
  # Scope of project
  EnvType:
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues:
      - test
      - dev
      - prd
    ConstraintDescription: must specify dev or mnt or prd.
  # Project ID Config
  ProjectId:
    Description: Project name id.
    Type: String
    MinLength: '0'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must specify Project id.
  # Create Certificate Name
  CertificateName:
    Description: The certificate name for SSL compliance
    Type: String
    MinLength: '3'
    MaxLength: '99'
    ConstraintDescription: must specify Certificate name
  # Set Creficate ARN
  CertificateARN:
    Description: Please enter the ARN of the created  CF certificate
    Type: String
    MinLength: '3'
    MaxLength: '99'
    ConstraintDescription: must specify Certificate name
  # Create Origin Certificate Name
  OriginCertificateName:
    Description: The certificate name for SSL compliance
    Type: String
    MinLength: '3'
    MaxLength: '99'
    ConstraintDescription: must specify Origin Certificate name

Resources:
  # Create CloudFront
  ClodFront:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        # set CNAME
        Aliases:
          - !Ref CertificateName
        Origins:
          - DomainName: !Ref OriginCertificateName
            Id: !Join ['-',[Custom, 'Ref': 'OriginCertificateName'] ]
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Join ['-', [Custom, 'Ref': 'OriginCertificateName'] ]
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true
          SmoothStreaming: false
        ViewerCertificate:
            AcmCertificateArn: !Ref CertificateARN
            SslSupportMethod: sni-only