AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a RDS Aurora cluster.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Configuration
        Parameters:
          - EnvType
          - ProjectId
      - Label:
          default: Database Configuration
        Parameters:
          - DBInstanceType
          - DBName
          - DBUser
          - DBPassword
          - DBSubnets1
          - DBSubnets2
          - DBSecurityGroup
    ParameterLabels:
      EnvType:
        default: Environment type.
      ProjectId:
        default: Project name id.
      DBInstanceType:
        default: Instance Type.
      DBName:
        default: DB name.
      DBUser:
        default: DB User name.
      DBPassword:
        default: DB Password.
      DBSubnets1:
        default: DB Subnet1.
      DBSubnets2:
        default: DB Subnet2.
      DBSecurityGroup:
        default: DB SecurityGroup

Parameters:
  # Scope of project
  EnvType:
    Description: Select Environment type.
    Default: dev
    Type: String
    AllowedValues:
      - test
      - dev
      - prd
    ConstraintDescription: must specify dev or mnt or prd.
  # Project ID Config
  ProjectId:
    Description: Please enter Project name id.
    Type: String
    MinLength: '0'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must specify Project id.
  # Set DB Instance Type
  DBInstanceType:
    Default:  db.r3.large
    Type: String
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.r3.large
      - db.r3.xlarge
      - db.r3.2xlarge
      - db.r3.4xlarge
      - db.r3.8xlarge
    Description: The instance type to use for the database.
  # Create DB Name
  DBName:
    NoEcho: false
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '10'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  # Create DB Master user
  DBUser:
    NoEcho: false
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  # Create DB Master user pass
  DBPassword:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  # Set DBSubnet1
  DBSubnets1:
    Description: The subnets to place database instances in.
    Type: AWS::EC2::Subnet::Id
  # Set DB Subnet2
  DBSubnets2:
    Description: The subnets to place database instances in.
    Type: AWS::EC2::Subnet::Id
  # Set DB Security Group
  DBSecurityGroup:
    Description: The Security Group to place DB
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  # Create DB Subnet Group
  RDSMultiAZSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Enable RDS Multi-AZ access.
      SubnetIds:
        - !Ref DBSubnets1
        - !Ref DBSubnets2
  # Create RDS Cluster
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      Engine: aurora
      DatabaseName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
  # Create Primary Instance
  RDSPrimaryInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: !Ref DBInstanceType
      DBInstanceIdentifier: !Join [ '-', [ 'Ref':'EnvType' , 'Ref':'ProjectId' ,'aurora-a' ] ]
  # Create Replica Instance
  RDSReplicaInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: !Ref DBInstanceType
      DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
      DBInstanceIdentifier: !Join [ '-', [ 'Ref':'EnvType' , 'Ref':'ProjectId' ,'aurora-c' ] ]



