AWSTemplateFormatVersion: 2010-09-09
Description: Creates a RDS Aurora cluster.
Parameters:
  DatabaseSubnets:
    Description: The subnets to place database instances in.
    Type: CommaDelimitedList
Resources:
  # Create DB Subnet Group
  RDSMultiAZSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Enable RDS Multi-AZ access.
      SubnetIds:
        - !Ref  DatabaseSubnets
  # # Create RDS Cluster
  # RDSCluster:
  #   Type: "AWS::RDS::DBCluster"
  #   Properties:
  #     # AvailabilityZones:
  #     #   - us-east-1a
  #     #   - us-east-1c
  #     Engine: aurora
  #     DatabaseName: !Ref DBName
  #     MasterUsername: !Ref DBUser
  #     MasterUserPassword: !Ref DBPassword
  #     DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
  #     VpcSecurityGroupIds:
  #       - !Ref RDSSecurityGroup
  # # Create Primary Instance
  # RDSPrimaryInstance:
  #   Type: "AWS::RDS::DBInstance"
  #   Properties:
  #     # AvailabilityZone: us-east-1a
  #     Engine: aurora
  #     DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
  #     DBClusterIdentifier: !Ref RDSCluster
  #     DBInstanceClass: !Ref DBInstanceType
  #     DBInstanceIdentifier: !Join [ "-", [ "Ref":"EnvType" , "Ref":"ProjectId" ,"aurora-a" ] ]
  # # Create Replica Instance
  # RDSReplicaInstance:
  #   Type: 'AWS::RDS::DBInstance'
  #   Properties:
  #     # AvailabilityZone: us-east-1c
  #     Engine: aurora
  #     DBClusterIdentifier: !Ref RDSCluster
  #     DBInstanceClass: !Ref DBInstanceType
  #     DBSubnetGroupName: !Ref RDSMultiAZSubnetGroup
  #     DBInstanceIdentifier: !Join [ "-", [ "Ref":"EnvType" , "Ref":"ProjectId" ,"aurora-c" ] ]



