AWSTemplateFormatVersion: 2010-09-09
Description: Creates a RDS Aurora cluster.
Parameters:
    DatabaseInstanceType:
        Default: db.t2.medium
        AllowedValues:
          - db.t2.small
          - db.t2.medium
          - db.r3.large
          - db.r3.xlarge
          - db.r3.2xlarge
          - db.r3.4xlarge
          - db.r3.8xlarge
        Description: The instance type to use for the database.
        Type: String
    DatabasePassword:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters.
        Description: The database admin account password.
        MaxLength: '30'
        MinLength: '8'
        NoEcho: 'true'
        Type: String
    DatabaseUsername:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters.
        Description: The database admin account user name.
        MaxLength: '16'
        MinLength: '1'
        Type: String
    DatabaseBackupRetentionPeriod:
        Type: String
        Default: 1
        AllowedValues:
            - 1
            - 10
            - 20
        Description: The database backup retention period in days.
    DatabaseSubnets:
        Description: The subnets to place database instances in.
        Type: List<String>
    VPCId:
        Type: String
        Description: VPC in which to launch the Aurora RDS Cluster.
Resources:
    DBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow Inbound Traffic to DB
            VpcId:
                Ref: VPCId
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: '3306'
                  ToPort: '3306'
                  CidrIp: 0.0.0.0/0
    StackAlarmTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: Stack Alarm Topic
    DatabaseSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: CloudFormation managed DB subnet group.
            SubnetIds:
                Ref: DatabaseSubnets
    DatabaseCluster:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora
            MasterUsername:
                Ref: DatabaseUsername
            MasterUserPassword:
                Ref: DatabasePassword
            BackupRetentionPeriod:
                Ref: DatabaseBackupRetentionPeriod
            PreferredBackupWindow: 01:00-02:30
            PreferredMaintenanceWindow: mon:03:00-mon:04:00
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            VpcSecurityGroupIds:
                - Ref: DBSecurityGroup
    DatabasePrimaryInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: aurora
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
    DatabaseReplicaInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: aurora
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup